version: '3'
services:
  configuration-server:
    container_name: configuration-server
    hostname: configuration-server
    image: dev-it/devit-configuration-server:latest
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - devit-network
    env_file:
      - .configuration_server_env
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    logging:
      driver: json-file

  eureka:
    container_name: eureka
    hostname: eureka
    image: dev-it/devit-eureka-server:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - devit-network
    logging:
        driver: json-file

networks:
  devit-network:
    driver: bridge